- repo: git://github.com/dnephin/pre-commit-golang
  sha: HEAD
  hooks:
    - id: go-fmt
    - id: go-vet
    - id: go-lint
    - id: validate-toml
    - id: no-go-testing
    - id: gometalinter

# fixmyjs doesn’t work with all lambdas
#- repo: git://github.com/pre-commit/mirrors-fixmyjs
#  sha: HEAD
#  hooks:
#    - id: fixmyjs
#      exclude: frontend/.generators/*

- repo: git://github.com/awebdeveloper/pre-commit-prettier
  sha: HEAD
  hooks:
    - id: prettier
      exclude: frontend/.generators/*

- repo: git://github.com/pre-commit/mirrors-jshint
  sha: HEAD
  hooks:
    - id: jshint
      exclude: frontend/.generators/*

